/**
 * Accessibility standards for testing
 */

export const a11yStandardsConfig = {
    rules: [
        { id: 'area-alt', enabled: true },
        { id: 'aria-allowed-attr', enabled: true },
        { id: 'aria-command-name', enabled: true },
        { id: 'aria-hidden-body', enabled: true },
        { id: 'aria-hidden-focus', enabled: true },
        { id: 'aria-input-field-name', enabled: true },
        { id: 'aria-meter-name', enabled: true },
        { id: 'aria-progressbar-name', enabled: true },
        { id: 'aria-required-attr', enabled: true },
        { id: 'aria-required-children', enabled: true },
        { id: 'aria-required-parent', enabled: true },
        { id: 'aria-roledescription', enabled: true },
        { id: 'aria-roles', enabled: true },
        { id: 'aria-toggle-field-name', enabled: true },
        { id: 'aria-tooltip-name', enabled: true },
        { id: 'aria-valid-attr-value', enabled: true },
        { id: 'aria-valid-attr', enabled: true },
        { id: 'audio-caption', enabled: true },
        { id: 'blink', enabled: true },
        { id: 'button-name', enabled: true },
        { id: 'bypass', enabled: true },
        { id: 'color-contrast', enabled: true },
        { id: 'definition-list', enabled: true },
        { id: 'dlitem', enabled: true },
        { id: 'document-title', enabled: true },
        { id: 'duplicate-id-active', enabled: true },
        { id: 'duplicate-id-aria', enabled: true },
        { id: 'duplicate-id', enabled: true },
        { id: 'form-field-multiple-labels', enabled: true },
        { id: 'frame-focusable-content', enabled: true },
        { id: 'frame-title', enabled: true },
        { id: 'html-has-lang', enabled: true },
        { id: 'html-lang-valid', enabled: true },
        { id: 'html-xml-lang-mismatch', enabled: true }, { id: 'image-alt', enabled: true },
        { id: 'input-button-name', enabled: true },
        { id: 'input-image-alt', enabled: true },
        { id: 'label', enabled: true }, { id: 'link-name', enabled: true },
        { id: 'list', enabled: true }, { id: 'listitem', enabled: true }, { id: 'marquee', enabled: true },
        { id: 'meta-refresh', enabled: true },
        { id: 'nested-interactive', enabled: true },
        { id: 'object-alt', enabled: true },
        { id: 'role-img-alt', enabled: true },
        { id: 'scrollable-region-focusable', enabled: true },
        { id: 'select-name', enabled: true },
        { id: 'server-side-image-map', enabled: true },
        { id: 'svg-img-alt', enabled: true },
        { id: 'd-headers-attr', enabled: true },
        { id: 'th-has-data-cells', enabled: true },
        { id: 'valid-lang', enabled: true },
        { id: 'video-caption', enabled: true },
        { id: 'autocomplete-valid', enabled: true },
        { id: 'avoid-inline-spacing', enabled: true },
        { id: 'empty-table-header', enabled: true },
        { id: 'accesskeys', enabled: true },
        { id: 'aria-allowed-role', enabled: true },
        { id: 'aria-dialog-name', enabled: true },
        { id: 'aria-text', enabled: true },
        { id: 'aria-treeitem-name', enabled: true },

        { id: 'frame-focusable-content', enabled: true },
        { id: 'frame-title', enabled: true },
        { id: 'html-has-lang', enabled: true },
        { id: 'html-lang-valid', enabled: true },
        { id: 'html-xml-lang-mismatch', enabled: true },
        { id: 'image-alt', enabled: true },
        { id: 'input-button-name', enabled: true },
        { id: 'input-image-alt', enabled: true },
        { id: 'label', enabled: true },
        { id: 'link-name', enabled: true },
        { id: 'list', enabled: true },
        { id: 'listitem', enabled: true },
        { id: 'marquee', enabled: true },
        { id: 'meta-refresh', enabled: true },
        { id: 'nested-interactive', enabled: true },
        { id: 'object-alt', enabled: true },
        { id: 'role-img-alt', enabled: true },
        { id: 'scrollable-region-focusable', enabled: true },
        { id: 'select-name', enabled: true },
        { id: 'server-side-image-map', enabled: true },
        { id: 'svg-img-alt', enabled: true },
        { id: 'd-headers-attr', enabled: true },
        { id: 'th-has-data-cells', enabled: true },
        { id: 'valid-lang', enabled: true },
        { id: 'video-caption', enabled: true },
        { id: 'autocomplete-valid', enabled: true },
        { id: 'avoid-inline-spacing', enabled: true },
        { id: 'empty-table-header', enabled: true },
        { id: 'accesskeys', enabled: true },
        { id: 'aria-allowed-role', enabled: true },
        { id: 'aria-dialog-name', enabled: true },
        { id: 'aria-text', enabled: true },
        { id: 'aria-treeitem-name', enabled: true }
    ]
};