name: Cypress E2E Tests
on:
  push:
    branches: [5-GitHub-Action]
  pull_request:
    branches: [main, master]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --force
      - uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
      - name: Run E2E tests
        run: npm run cy:run
      - name: Generate Allure report
        run: npm run allure:report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
