name: Cypress E2E Tests
on:
  push:
    branches: [5-GitHub-Action]
  pull_request:
    branches: [main, master]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - run: npm ci --force

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v6
        with:
          start: npm start &
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/e2e/*
          config-file: cypress.config.ts
      - name: Run E2E tests
        run: npm run cy:run
      - name: Generate Allure report
        run: npm run allure:report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
